### ISSUE TITLE
Code is not compatible with AM 7.1.1

### ISSUE THREAD

**Issue by dfiguerox** [DennisAndradeRJ/html-node#1]
Deployed the jar file against a 7.1.1 instance. It loaded correctly and was able to get all the details setup. However, when running the code AM throws an error with the relevant part being:

```
Caused by: java.lang.NoSuchMethodError: 'char[] com.example.OTPHttpEmailSenderAuthNode.OTPHttpEmailSenderAuthNode$Config.password()'
	at com.example.OTPHttpEmailSenderAuthNode.OTPHttpEmailSenderAuthNode.sendEmail(OTPHttpEmailSenderAuthNode.java:141)
	at com.example.OTPHttpEmailSenderAuthNode.OTPHttpEmailSenderAuthNode.process(OTPHttpEmailSenderAuthNode.java:130)
```

I am no Java expert but it seems that the `password()` method from `org.forgerock.openam.auth.nodes.SmtpBaseConfig` is not of the correct signature in newer versions of AM.

**Comment by cuzic4n** [comment]
Same issue here with 7.2.0

**Comment by DennisAndradeRJ** [comment]
Thanks for reporting this issue. A new version of the HTML mail sender node has been released with support for AM 7.x.
